export {default as Home} from './Home/Home'
export{default as Login} from '../Pages/Login/Login'
export {default as SignUp} from '../Pages/SignUp/SignUp'
export {default as HomeSignedin} from '../Pages/HomeSignedin/HomeSignedin'
export {default as Verify} from '../Pages/Verify/Verify'